// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tjrj.Biblioteca.Infra.Contexts;

#nullable disable

namespace Tjrj.Biblioteca.Infra.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    partial class BibliotecaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.Assunto", b =>
                {
                    b.Property<int>("CodAs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAs");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAs"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Descricao");

                    b.HasKey("CodAs");

                    b.ToTable("Assunto", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("CodAu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodAu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAu"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Nome");

                    b.HasKey("CodAu");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.FormaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Forma_Compra", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("Codl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Codl");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codl"));

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("AnoPublicacao");

                    b.Property<int>("Edicao")
                        .HasColumnType("int")
                        .HasColumnName("Edicao");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Editora");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Titulo");

                    b.HasKey("Codl");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.LivroAssunto", b =>
                {
                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int")
                        .HasColumnName("Livro_Codl");

                    b.Property<int>("Assunto_CodAs")
                        .HasColumnType("int")
                        .HasColumnName("Assunto_CodAs");

                    b.HasKey("Livro_Codl", "Assunto_CodAs");

                    b.HasIndex("Assunto_CodAs");

                    b.ToTable("Livro_Assunto", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.LivroAutor", b =>
                {
                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int")
                        .HasColumnName("Livro_Codl");

                    b.Property<int>("Autor_CodAu")
                        .HasColumnType("int")
                        .HasColumnName("Autor_CodAu");

                    b.HasKey("Livro_Codl", "Autor_CodAu");

                    b.HasIndex("Autor_CodAu");

                    b.ToTable("Livro_Autor", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.LivroPreco", b =>
                {
                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int")
                        .HasColumnName("Livro_Codl");

                    b.Property<int>("FormaCompra_Id")
                        .HasColumnType("int")
                        .HasColumnName("FormaCompra_Id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Livro_Codl", "FormaCompra_Id");

                    b.HasIndex("FormaCompra_Id");

                    b.ToTable("Livro_Preco", (string)null);
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.LivroAssunto", b =>
                {
                    b.HasOne("Tjrj.Biblioteca.Domain.Entities.Assunto", "Assunto")
                        .WithMany("Livros")
                        .HasForeignKey("Assunto_CodAs")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tjrj.Biblioteca.Domain.Entities.Livro", "Livro")
                        .WithMany("Assuntos")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.LivroAutor", b =>
                {
                    b.HasOne("Tjrj.Biblioteca.Domain.Entities.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tjrj.Biblioteca.Domain.Entities.Livro", "Livro")
                        .WithMany("Autores")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.LivroPreco", b =>
                {
                    b.HasOne("Tjrj.Biblioteca.Domain.Entities.FormaCompra", "FormaCompra")
                        .WithMany("Precos")
                        .HasForeignKey("FormaCompra_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tjrj.Biblioteca.Domain.Entities.Livro", "Livro")
                        .WithMany("Precos")
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormaCompra");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.Assunto", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.Autor", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.FormaCompra", b =>
                {
                    b.Navigation("Precos");
                });

            modelBuilder.Entity("Tjrj.Biblioteca.Domain.Entities.Livro", b =>
                {
                    b.Navigation("Assuntos");

                    b.Navigation("Autores");

                    b.Navigation("Precos");
                });
#pragma warning restore 612, 618
        }
    }
}
